### ISSUE TITLE
Update Wire dependency

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/Rebus.Wire#1]
The next version of Wire will most likely contain a fix for a `NullReferenceException` that comes when trying to deserialize stuff on .NET Core.

Checkout [this PR](https://github.com/rogeralsing/Wire/pull/147).

When the new version is out, the Wire dependency must be updated.

**Comment by allrameest** [comment]
@mookid8000 have you looked at Hyperion? It seems to be a fork of Wire that is maintained by the Akka.NET team. It works well with .NET 3.1.
https://github.com/akkadotnet/Hyperion
https://www.nuget.org/packages/Hyperion/

**Comment by mookid8000** [comment]
@allrameest thanks for the link! Rebus now has a Hyperion serializer 👉 https://github.com/rebus-org/Rebus.Hyperion

Just go
```psh
install-package rebus.hyperion
```
followed by
```csharp
Configure.With(...)
	.(...)
	.Serialization(s => s.UseHyperion())
	.Start();
```
and then you'll have Hyperion-serialized messages!
